kind: SecretClaim
apiVersion: vaultproject.io/v1
metadata:
  name: example-dot-com
spec:
  type: kubernetes.io/tls
  path: pki/issue/example
  renew: 30
  data:
    common_name: "example.com"
    ttl: 1m
