# Examples of what will and won't work if using a namespace-prefix
# --namespace-prefix=secret/cluster-name/
---
kind: SecretClaim
apiVersion: vaultproject.io/v1
metadata:
  name: allowed
  namespace: example
spec:
  type: Opaque
  path: secret/cluster-name/example/key
---
kind: SecretClaim
apiVersion: vaultproject.io/v1
metadata:
  name: not-allowed
  namespace: othernamespace
spec:
  type: Opaque
  path: secret/cluster-name/example/key
---
kind: SecretClaim
apiVersion: vaultproject.io/v1
metadata:
  name: allowed-because-outside-of-prefix
  namespace: example
spec:
  type: Opaque
  path: secret/other-secret-path/key
